version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=noriega
      - POSTGRES_PASSWORD=server2023$
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  
  app:
    image: dnoriega20/api:v1
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["sh", "-c", "npm run migrations:run && npm run seeders:run-all && npm start"]
